### ISSUE TITLE
SweetFX+DXVK

### ISSUE THREAD

**Issue by Adibo88** [CeeJayDK/SweetFX#6]
Can I use use SweetFX on its own, without installing ReShade? The reason I'm asking is that ReShade cannot be used along with DXVK, but SweetFX itself can be chained with other libraries, and I want to use it with DXVK to get some performance boost in some badly optimized dx11-games.

**Comment by LyrixTheDj** [comment]
>...I want to use it with DXVK ...
You can try [vkBasalt](https://github.com/DadSchoorse/vkBasalt) under GNU/Linux

**Comment by Zacam** [comment]
I've had no issue with using ReShade along with DXVK by naming ReShade as "ReShade.asi" instead of d3d#/dxgi.dll
That'll be contingent on if the use case is using a dinput8.dll injector or not that will load ASI's though.

**Comment by nullfrctl** [comment]
You can use it with dxgi.dll, too. You just need d3dcompiler_47.dll as well. You can find online sources for where to get it.

**Comment by CeeJayDK** [comment]
I have no issues with using Reshade and DXVK together - Simply install Reshade for Vulkan for that game.
